#!/bin/env python3
import json
import base64
def decodeOIDC(thing):
  junk={}
  try:
    decoded = base64.b64decode(str(thing['X-Id-Token']))
    junk=decoded.decode("utf-8")
    junk=json.loads(junk)
  except Exception as e:
    junk={"exception": str(e)}
    pass
  return junk

#print(decodeOIDC("eyJpYXQiOjE2MTI4ODY1MjAsImlzcyI6Imh0dHBzOlwvXC9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tXC80NGI3OWE2Ny1kOTcyLTQ5YmEtOTE2Ny04ZWIwNWY3NTRhMWFcL3YyLjAiLCJyaCI6IjAuQVJjQVo1cTNSSExadWttUlo0NndYM1ZLR2h2YlBvYjdmVWRMbXpleXNjVGtBbk1YQURJLiIsIm5vbmNlIjoiM2M2YjU5YmExYTFlNmY4MDUyZTM2OTFjOTU4ODE3ZjQiLCJlbWFpbCI6Ik1hdHQuQ2VuZ2ljQHNoZXJ3aW4uY29tIiwidWlkIjoibXhjNTY0Iiwic3ViIjoiQjNTNlRLOUw1Y2dJMjZrbExDNWRfLVA0eWNhUkVzSzlfXzhSQlg4VHUwTSIsIm5iZiI6MTYxMjg4NjUyMCwib2lkIjoiM2ZkOTNjODMtZmRhNi00YmQ4LTgzMTItZjE1ZTIwZTlhZTgwIiwiYXVkIjoiODYzZWRiMWItN2RmYi00YjQ3LTliMzctYjJiMWM0ZTQwMjczIiwidmVyIjoiMi4wIiwidGlkIjoiNDRiNzlhNjctZDk3Mi00OWJhLTkxNjctOGViMDVmNzU0YTFhIiwibmFtZSI6Ik1hdHQgQ2VuZ2ljIiwiZXhwIjoxNjEyODkwNDIwLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJNYXR0LkNlbmdpY0BzaGVyd2luLmNvbSIsImh0dHA6XC9cL3NjaGVtYXMueG1sc29hcC5vcmdcL3dzXC8yMDA1XC8wNVwvaWRlbnRpdHlcL2NsYWltc1wvc3VybmFtZSI6IkNlbmdpYyIsImh0dHA6XC9cL3NjaGVtYXMueG1sc29hcC5vcmdcL3dzXC8yMDA1XC8wNVwvaWRlbnRpdHlcL2NsYWltc1wvZ2l2ZW5uYW1lIjoiTWF0dCIsInV0aSI6IkhGWnNDTFktSVVPUnJ2aEotdGZaQUEifQ=="))
